<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Weave.Adapter/Weave.Adapter.csproj" />
    <ProjectReference Include="../../src/Weave.Adapter.FSharp/Weave.Adapter.FSharp.fsproj" />
    <ProjectReference Include="../../src/Weave.Adapter.Model/Weave.Adapter.Model.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
