// Package dot renders bounded semantic graph views as deterministic Graphviz
// DOT without invoking Graphviz or another external process.
package dot

import (
	"cmp"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/TheFellow/weave/internal/graph"
)

// View is the complete bounded neighborhood presented in one DOT document.
type View struct {
	Focus     string
	Nodes     []string
	Symbols   []graph.Symbol
	Edges     []graph.Edge
	Truncated bool
	// OmitTitle lets an embedding surface supply its own accessible heading
	// without duplicating the focus inside the Graphviz layout.
	OmitTitle bool
}

type node struct {
	id, label, stable, kind, provider, evidence string
	materialized                                bool
}

type renderedEdge struct {
	edge  graph.Edge
	count int
}

// Write emits a complete deterministic directed graph. Semantic identifiers
// are retained in tooltips. DOT and SVG identifiers are deterministic hashes
// of semantic identities so browser renderers can preserve object constancy
// while a bounded neighborhood changes.
func Write(writer io.Writer, view View) error {
	if view.Focus == "" {
		return fmt.Errorf("DOT view focus is empty")
	}
	nodes := collectNodes(view)
	if len(nodes) == 0 {
		return fmt.Errorf("DOT view has no nodes")
	}
	ids := make(map[string]string, len(nodes))
	labelCounts := make(map[string]int, len(nodes))
	for _, value := range nodes {
		ids[value.id] = stableID("n", value.id)
		labelCounts[nodeLabelKey(value)]++
	}
	incoming, outgoing := reachability(view.Focus, view.Edges)

	var output strings.Builder
	output.WriteString("// Generated by weave; render with: dot -Tsvg graph.dot -o graph.svg\n")
	output.WriteString("digraph weave {\n")
	output.WriteString("  graph [id=\"weave-graph\", rankdir=LR, charset=\"UTF-8\", bgcolor=\"#FFFFFF\", fontname=\"Helvetica\", fontsize=12, labelloc=t, labeljust=l, pad=0.25, nodesep=0.35, ranksep=0.75, splines=polyline, overlap=false, compound=true, newrank=true];\n")
	output.WriteString("  node [shape=box, fontname=\"Helvetica\", fontsize=10, style=\"rounded,filled\", color=\"#5B6573\", fillcolor=\"#FFFFFF\", fontcolor=\"#1F2937\", margin=\"0.12,0.08\"];\n")
	output.WriteString("  edge [fontname=\"Helvetica\", fontsize=9, color=\"#6B7280\", fontcolor=\"#4B5563\", arrowsize=0.7, penwidth=1.1];\n")
	focusLabel := view.Focus
	for _, value := range nodes {
		if value.id == view.Focus {
			focusLabel = value.label
			break
		}
	}
	title := "Weave · " + singleLine(focusLabel)
	if view.Truncated {
		title += "\nbounded result · additional nodes or edges omitted"
	}
	if !view.OmitTitle {
		fmt.Fprintf(&output, "  label=%s;\n", quote(title))
	}

	providers := make(map[string][]node)
	for _, value := range nodes {
		providers[value.provider] = append(providers[value.provider], value)
	}
	providerNames := make([]string, 0, len(providers))
	for provider := range providers {
		providerNames = append(providerNames, provider)
	}
	slices.Sort(providerNames)
	for _, provider := range providerNames {
		fmt.Fprintf(&output, "  subgraph %s {\n", stableID("cluster", provider))
		fmt.Fprintf(&output, "    id=%s; label=%s; color=\"#D1D5DB\"; fontcolor=\"#4B5563\"; fontsize=10; style=\"rounded\";\n", quote(svgID("cluster", provider)), quote(provider))
		for _, value := range providers[provider] {
			attributes := nodeAttributes(value, NodeSVGID(value.id), value.id == view.Focus, incoming[value.id], outgoing[value.id], labelCounts[nodeLabelKey(value)] > 1)
			fmt.Fprintf(&output, "    %s [%s];\n", ids[value.id], attributes)
		}
		output.WriteString("  }\n")
	}

	for _, rendered := range collapseEdges(view.Edges) {
		edge := rendered.edge
		from, fromOK := ids[edge.From]
		to, toOK := ids[edge.To]
		if !fromOK || !toOK {
			continue
		}
		fmt.Fprintf(&output, "  %s -> %s [%s];\n", from, to, edgeAttributes(edge, rendered.count, svgID("edge", edgeCollapseKey(edge))))
	}
	output.WriteString("}\n")
	_, err := io.WriteString(writer, output.String())
	return err
}

func collectNodes(view View) []node {
	byID := make(map[string]node, len(view.Nodes)+len(view.Edges)*2)
	for _, symbol := range view.Symbols {
		provider := symbol.Provider
		if provider == "" {
			provider = "unattributed"
		}
		label := symbol.DisplayName
		if label == "" {
			label = symbol.StableName
		}
		if label == "" {
			label = symbol.ID
		}
		stable := symbol.StableName
		if stable == "" {
			stable = symbol.ID
		}
		byID[symbol.ID] = node{
			id: symbol.ID, label: label, stable: stable, kind: symbol.Kind,
			provider: provider, evidence: string(symbol.Evidence), materialized: true,
		}
	}
	addExternal := func(id string) {
		if id == "" {
			return
		}
		if _, ok := byID[id]; ok {
			return
		}
		byID[id] = node{id: id, label: externalLabel(id), stable: id, kind: "external", provider: "external endpoints"}
	}
	for _, id := range view.Nodes {
		addExternal(id)
	}
	addExternal(view.Focus)
	for _, edge := range view.Edges {
		addExternal(edge.From)
		addExternal(edge.To)
	}
	result := make([]node, 0, len(byID))
	for _, value := range byID {
		result = append(result, value)
	}
	slices.SortFunc(result, func(a, b node) int {
		if value := strings.Compare(a.provider, b.provider); value != 0 {
			return value
		}
		if value := strings.Compare(strings.ToLower(a.label), strings.ToLower(b.label)); value != 0 {
			return value
		}
		return strings.Compare(a.id, b.id)
	})
	return result
}

func nodeAttributes(value node, graphvizID string, focus, incoming, outgoing, duplicateLabel bool) string {
	fill := "#FFFFFF"
	switch {
	case focus:
		fill = "#F6C85F"
	case incoming && outgoing:
		fill = "#F4CCCC"
	case incoming:
		fill = "#D9EAD3"
	case outgoing:
		fill = "#D9D2E9"
	}
	style := "rounded,filled"
	color := "#5B6573"
	if !value.materialized {
		style = "rounded,filled,dashed"
		color = "#9CA3AF"
	}
	label := tail(singleLine(value.label), 48)
	if detail := nodeDetail(value, duplicateLabel); detail != "" {
		label += "\n" + detail
	}
	tooltip := value.stable
	if value.id != value.stable {
		tooltip += "\nid: " + value.id
	}
	if value.kind != "" {
		tooltip += "\nkind: " + value.kind
	}
	if value.evidence != "" {
		tooltip += "\nevidence: " + value.evidence
	}
	return strings.Join([]string{
		"id=" + quote(graphvizID),
		"label=" + quote(label),
		"tooltip=" + quote(tooltip),
		"shape=" + quote(nodeShape(value.kind)),
		"style=" + quote(style),
		"fillcolor=" + quote(fill),
		"color=" + quote(color),
	}, ", ")
}

func nodeDetail(value node, duplicateLabel bool) string {
	if !value.materialized {
		return "unmaterialized endpoint"
	}
	if value.kind == "" || value.kind == "external" {
		if duplicateLabel {
			return compactContext(value.stable)
		}
		return ""
	}
	if duplicateLabel {
		return value.kind + " · " + compactContext(value.stable)
	}
	return value.kind
}

func nodeLabelKey(value node) string {
	return strings.Join([]string{value.provider, strings.ToLower(singleLine(value.label)), value.kind}, "\x00")
}

func compactContext(value string) string {
	value = singleLine(value)
	if index := strings.LastIndexByte(value, '/'); index >= 0 {
		value = value[index+1:]
	}
	for _, marker := range []string{".package.", ".type.", ".method.", ".field.", ".function.", ".variable.", ".constant."} {
		value = strings.ReplaceAll(value, marker, ".")
	}
	return tail(value, 40)
}

func nodeShape(kind string) string {
	switch kind {
	case "workspace", "directory", "package", "module", "namespace":
		return "folder"
	case "document", "file", "section", "url", "route", "topic", "series":
		return "note"
	case "class", "struct", "interface", "trait", "type", "enum", "union":
		return "component"
	case "test", "test-case", "test-suite":
		return "tab"
	case "code-block":
		return "box3d"
	default:
		return "box"
	}
}

func edgeAttributes(edge graph.Edge, count int, graphvizID string) string {
	style, penwidth := "solid", "1.1"
	switch edge.Evidence {
	case graph.EvidenceGenerated:
		style = "dashed"
		penwidth = "1.5"
	case graph.EvidenceDeclared:
		penwidth = "1.4"
	case graph.EvidenceInferred, graph.EvidenceSyntactic:
		style = "dashed"
	case graph.EvidenceAmbiguous:
		style = "dotted"
		penwidth = "1.6"
	}
	label := string(edge.Kind)
	tooltip := label
	if count > 1 {
		label += fmt.Sprintf(" ×%d", count)
		tooltip += fmt.Sprintf("\n%d equivalent source edges", count)
	}
	if edge.Evidence != "" {
		tooltip += "\nevidence: " + string(edge.Evidence)
	}
	if edge.Provider != "" {
		tooltip += "\nprovider: " + edge.Provider
	}
	if edge.ID != "" {
		tooltip += "\nid: " + edge.ID
	}
	return strings.Join([]string{
		"id=" + quote(graphvizID),
		"label=" + quote(label),
		"tooltip=" + quote(tooltip),
		"color=" + quote(edgeColor(edge.Kind)),
		"style=" + quote(style),
		"penwidth=" + penwidth,
	}, ", ")
}

func collapseEdges(edges []graph.Edge) []renderedEdge {
	byKey := make(map[string]renderedEdge, len(edges))
	for _, edge := range edges {
		key := edgeCollapseKey(edge)
		value := byKey[key]
		if value.count == 0 || edge.ID < value.edge.ID {
			value.edge = edge
		}
		value.count++
		byKey[key] = value
	}
	result := make([]renderedEdge, 0, len(byKey))
	for _, value := range byKey {
		result = append(result, value)
	}
	slices.SortFunc(result, func(a, b renderedEdge) int {
		return cmp.Or(graph.CompareEdges(a.edge, b.edge), cmp.Compare(a.count, b.count))
	})
	return result
}

func edgeCollapseKey(edge graph.Edge) string {
	return strings.Join([]string{edge.From, edge.To, string(edge.Kind), string(edge.Evidence), edge.Provider}, "\x00")
}

func stableID(namespace, semanticID string) string {
	return namespace + "_" + digestID(semanticID)
}

func svgID(namespace, semanticID string) string {
	return "weave-" + namespace + "-" + digestID(semanticID)
}

// NodeSVGID returns the stable SVG identity emitted for a semantic graph node.
// Interactive consumers use it to map Graphviz elements back to graph targets.
func NodeSVGID(semanticID string) string {
	return svgID("node", semanticID)
}

// EdgeSVGID returns the stable SVG identity emitted for the collapsed visual
// edge containing edge. Equivalent provider/evidence facts intentionally map
// to one element; callers can retain every source fact under this key.
func EdgeSVGID(edge graph.Edge) string {
	return svgID("edge", edgeCollapseKey(edge))
}

func digestID(value string) string {
	digest := sha256.Sum256([]byte(value))
	// 128 bits keeps identifiers compact while making accidental collision
	// across even very large local indexes vanishingly unlikely.
	return hex.EncodeToString(digest[:16])
}

func edgeColor(kind graph.EdgeKind) string {
	switch kind {
	case graph.EdgeImports, graph.EdgeDependsOn:
		return "#6D5BD0"
	case graph.EdgeExtends, graph.EdgeImplements, graph.EdgeInstantiates:
		return "#2E8B57"
	case graph.EdgeDocuments, graph.EdgeLinksTo, graph.EdgeEmbeds, graph.EdgeResolvesTo, graph.EdgeExposes:
		return "#008C95"
	case graph.EdgeGenerates:
		return "#D97706"
	case graph.EdgeTests:
		return "#2563EB"
	case graph.EdgeReads, graph.EdgeWrites:
		return "#A23B72"
	default:
		return "#6B7280"
	}
}

func reachability(focus string, edges []graph.Edge) (map[string]bool, map[string]bool) {
	forward := make(map[string][]string)
	reverse := make(map[string][]string)
	for _, edge := range edges {
		forward[edge.From] = append(forward[edge.From], edge.To)
		reverse[edge.To] = append(reverse[edge.To], edge.From)
	}
	walk := func(adjacency map[string][]string) map[string]bool {
		seen := map[string]bool{focus: true}
		queue := []string{focus}
		for len(queue) != 0 {
			current := queue[0]
			queue = queue[1:]
			next := append([]string(nil), adjacency[current]...)
			slices.Sort(next)
			for _, id := range next {
				if !seen[id] {
					seen[id] = true
					queue = append(queue, id)
				}
			}
		}
		delete(seen, focus)
		return seen
	}
	return walk(reverse), walk(forward)
}

// quote emits a Graphviz quoted string and prevents source backslashes from
// becoming escString substitutions such as \N, \E, or \L.
func quote(value string) string {
	var output strings.Builder
	output.WriteByte('"')
	for len(value) != 0 {
		current, size := utf8.DecodeRuneInString(value)
		value = value[size:]
		switch current {
		case '\\':
			output.WriteString(`\\`)
		case '"':
			output.WriteString(`\"`)
		case '\n':
			output.WriteString(`\n`)
		default:
			if current < 0x20 || current == 0x7f {
				output.WriteByte(' ')
			} else {
				output.WriteRune(current)
			}
		}
	}
	output.WriteByte('"')
	return output.String()
}

func singleLine(value string) string {
	return strings.Join(strings.Fields(value), " ")
}

func externalLabel(id string) string {
	prefix, suffix, found := strings.Cut(id, ":")
	if found && (prefix == "go" || prefix == "go-external") && len(suffix) == 64 && isHex(suffix) {
		return "external · " + suffix[:12]
	}
	return tail(singleLine(id), 64)
}

func isHex(value string) bool {
	for _, current := range value {
		if !((current >= '0' && current <= '9') || (current >= 'a' && current <= 'f') || (current >= 'A' && current <= 'F')) {
			return false
		}
	}
	return value != ""
}

func tail(value string, limit int) string {
	values := []rune(value)
	if len(values) <= limit {
		return value
	}
	return "…" + string(values[len(values)-limit+1:])
}
